# Generated by Django 2.0.4 on 2018-04-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lession_name', models.CharField(max_length=15)),
                ('lession_credit', models.IntegerField()),
                ('lession_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('xuehao', models.CharField(max_length=9)),
                ('subject', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=5)),
                ('native_place', models.CharField(max_length=15)),
            ],
        ),
    ]
