# Generated by Django 2.0.4 on 2018-04-12 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=10)),
                ('teacher_sex', models.CharField(max_length=2)),
                ('teacher_ID', models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='lession',
            name='lession_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.Teacher'),
        ),
    ]
