# Generated by Django 2.0.4 on 2018-04-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20180412_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_ID',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=9, null=True, verbose_name='教工号'),
        ),
        migrations.AlterField(
            model_name='lession',
            name='lession_credit',
            field=models.IntegerField(verbose_name='学分'),
        ),
        migrations.AlterField(
            model_name='lession',
            name='lession_name',
            field=models.CharField(max_length=15, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='lession',
            name='lession_time',
            field=models.IntegerField(verbose_name='学时'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20, verbose_name='学生姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='native_place',
            field=models.CharField(max_length=15, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(max_length=5, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(max_length=20, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='xuehao',
            field=models.CharField(max_length=9, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(max_length=10, verbose_name='老师姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_sex',
            field=models.CharField(max_length=2, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='score',
            name='lession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Lession'),
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Student'),
        ),
    ]
